=== nicoleSv/Human-Resources-Manager-Catalogue/DTD_HumanResourceManager_1_61987_61999.dtd
<?xml version="1.0" encoding="utf-8"?>
	<!ELEMENT company (about, levels)>
	<!ATTLIST company name CDATA #REQUIRED>

	<!ELEMENT about (logo, information,products,perspectives)>
	<!ELEMENT logo (image)>
	<!ELEMENT information (#PCDATA)>
	<!ELEMENT products (#PCDATA)>
	<!ELEMENT perspectives (#PCDATA)>
	
	<!ELEMENT levels (topLevel, midLevel, lowLevel)>

	<!ELEMENT employeeList (employee+)>
	<!ELEMENT employee (image, name,telephone,age,salary,hireDate)>
	<!ATTLIST employee ID CDATA #REQUIRED>
	<!ATTLIST employee experience (senior|mid|junior|intern) #IMPLIED>
	<!ATTLIST employee workWeek (fullTime|partTime) #REQUIRED>

	<!ELEMENT name (firstName, midName, lastName)>
	<!ELEMENT firstName (#PCDATA)>
	<!ELEMENT midName (#PCDATA)>
	<!ELEMENT lastName (#PCDATA)>
	<!ELEMENT telephone (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT salary (#PCDATA)>
	<!ELEMENT hireDate (#PCDATA)>

	<!ELEMENT topLevel (boardOfDirectors,chiefOfficer,president,vicePresident)>
	<!ELEMENT boardOfDirectors (employeeList)>
	<!ELEMENT chiefOfficer (employee)>
	<!ELEMENT president (employee)>
	<!ELEMENT vicePresident (employee)>

	<!ELEMENT midLevel (departmentsList)>
	<!ELEMENT departmentsList (department+)>

	<!ELEMENT department (subdepartment+|employeeList)>
	<!ATTLIST department name CDATA #REQUIRED>
	<!ATTLIST department image_src ENTITY #REQUIRED>
	<!ATTLIST department diagram_src ENTITY #IMPLIED>
	<!ELEMENT subdepartment (employeeList)>
	<!ATTLIST subdepartment name CDATA #REQUIRED>
	
	<!ELEMENT lowLevel (cleaningStaff, stationaryStaff)>
	<!ELEMENT cleaningStaff (employeeList)>
	<!ELEMENT stationaryStaff (employeeList)>
	
	<!NOTATION jpg PUBLIC "image/jpeg">
	<!ELEMENT image EMPTY>
	<!ATTLIST image src ENTITY #REQUIRED>

=== nicoleSv/Human-Resources-Manager-Catalogue/XML_HumanResourceManager_1_61987_61999.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XSL_HumanResourceManager.xsl"?>

<!DOCTYPE company SYSTEM "DTD_HumanResourceManager_1_61987_61999.dtd" [
	<!ENTITY companyLogo SYSTEM "images/logo.jpg" NDATA jpg>
	<!ENTITY face1 SYSTEM "images/1.jpg" NDATA jpg>
	<!ENTITY face2 SYSTEM "images/2.jpg" NDATA jpg>
	<!ENTITY face3 SYSTEM "images/3.jpg" NDATA jpg>
	<!ENTITY face4 SYSTEM "images/4.jpg" NDATA jpg>
	<!ENTITY face5 SYSTEM "images/5.jpg" NDATA jpg>
	<!ENTITY face6 SYSTEM "images/6.jpg" NDATA jpg>
	<!ENTITY face7 SYSTEM "images/7.jpg" NDATA jpg>
	<!ENTITY face8 SYSTEM "images/8.jpg" NDATA jpg>
	<!ENTITY face9 SYSTEM "images/9.jpg" NDATA jpg>
	<!ENTITY face10 SYSTEM "images/10.jpg" NDATA jpg>
	<!ENTITY face11 SYSTEM "images/11.jpg" NDATA jpg>
	<!ENTITY face12 SYSTEM "images/12.jpg" NDATA jpg>
	<!ENTITY face13 SYSTEM "images/13.jpg" NDATA jpg>
	<!ENTITY face14 SYSTEM "images/14.jpg" NDATA jpg>
	<!ENTITY face15 SYSTEM "images/15.jpg" NDATA jpg>
	<!ENTITY face16 SYSTEM "images/16.jpg" NDATA jpg>
	<!ENTITY face17 SYSTEM "images/17.jpg" NDATA jpg>
	<!ENTITY dep1 SYSTEM "images/marketing.jpg" NDATA jpg>
	<!ENTITY dep2 SYSTEM "images/sales.jpg" NDATA jpg>
	<!ENTITY dep3 SYSTEM "images/finance.jpg" NDATA jpg>
	<!ENTITY dep4 SYSTEM "images/legal.jpg" NDATA jpg>
	<!ENTITY dep5 SYSTEM "images/technology.jpg" NDATA jpg>
	<!ENTITY dep6 SYSTEM "images/support.jpg" NDATA jpg>
	<!ENTITY dep7 SYSTEM "images/hr.jpg" NDATA jpg>
	<!ENTITY dep8 SYSTEM "images/admin.jpg" NDATA jpg>
	<!ENTITY diagram1 SYSTEM "images/diagram1.jpg" NDATA jpg>
	<!ENTITY diagram2 SYSTEM "images/diagram2.jpg" NDATA jpg>
	<!ENTITY diagram3 SYSTEM "images/diagram3.jpg" NDATA jpg>
	<!ENTITY diagram4 SYSTEM "images/diagram4.jpg" NDATA jpg>
	<!ENTITY diagram5 SYSTEM "images/diagram5.jpg" NDATA jpg>
	<!ENTITY diagram6 SYSTEM "images/diagram6.jpg" NDATA jpg>
	<!ENTITY diagram7 SYSTEM "images/diagram7.jpg" NDATA jpg>
]>

<company name="Gaming Fox">
	<about>
		<logo>
			<image src="companyLogo"></image>
		</logo>

		<information>
			In a small office above a bar in Vancouver’s funky, newly resurgent Yaletown district, burgeoning game developers Alex Garden and Luke Moloney, mother and father’s PewDiePie, establish a gaming studio called Gaming Fox. Their vision for the studio was simple: become the world's best RTS studio. From the outset, Gaming Fox sought to balance the priorities of people and products while creating the best entertainment software available. A philosophy that clearly resonates given that five of the 39 employees who were part of Gaming Fox’s inception, remain with the company to this day.
		</information>

		<products>
			For more than 30 years, Gaming Fox has been changing the way people play.  In the process, we have built one of the largest portfolios of recognized brands and today we are one of the most valuable interactive entertainment companies in the world.  We have continue to thrive as a leading digital entertainment provider whose games appeal to a variety of gamers.

		</products>
		
		<perspectives>
		At Gaming Fox, we want to make great games that sell, and we wouldn’t be able to do it without our people. We achieve our success through our immensely talented development teams, and the operational expertise of our management, marketing, and corporate services. And most importantly we are gamers who develop products for gamers.We believe that creativity sparks innovation and inspires our employees to think differently and challenge the status quo. Whether it’s the kind of products we develop, our approach to sustainability, or the manner in which we give back to our communities, Gaming Fox finds unique ways to bring people together to fuel creative thinking.
		</perspectives>
	</about>

	<levels>
		<topLevel>
			<boardOfDirectors>
				<employeeList>
					<employee ID="1" workWeek="fullTime">
						<image src="face1"></image>
						<name>
							<firstName>Felix</firstName>
							<midName>Arvid Ulf</midName>
							<lastName>Kjellberg (PewDiePie)</lastName>
						</name>
						<telephone>507-76-0410</telephone>
						<age>29</age>
						<salary>$18,300</salary>
						<hireDate>7/28/2000</hireDate>
					</employee>

					<employee ID="2" workWeek="fullTime">
						<image src="face2"></image>
						<name>
							<firstName>Jason</firstName>
							<midName>Anthony</midName>
							<lastName>Lamb</lastName>
						</name>
						<telephone>202-544-6247</telephone>
						<age>30</age>
						<salary>$15,100</salary>
						<hireDate>06/28/1990</hireDate>
					</employee>

					<employee ID="3" workWeek="fullTime">
						<image src="face3"></image>
						<name>
							<firstName>James</firstName>
							<midName>Henry</midName>
							<lastName>Keller</lastName>
						</name>
						<telephone>202-544-6000</telephone>
						<age>50</age>
						<salary>$12,100</salary>
						<hireDate>10/28/2000</hireDate>
					</employee>
				</employeeList>
			</boardOfDirectors>

			<chiefOfficer>
				<employee ID="4"  workWeek="fullTime">
					<image src="face4"></image>
					<name>
						<firstName>Oliver</firstName>
						<midName>Rose</midName>
						<lastName>Horman</lastName>
					</name>
					<telephone>202-103-6000</telephone>
					<age>25</age>
					<salary>$8,300</salary>
					<hireDate>02/28/1990</hireDate>
				</employee>
			</chiefOfficer>

			<president>
				<employee ID="5"  workWeek="fullTime">
					<image src="face5"></image>
					<name>
						<firstName>Felix</firstName>
						<midName>Arvid Ulf</midName>
						<lastName>Kjellberg</lastName>
					</name>
					<telephone>088-888-8888</telephone>
					<age>29</age>
					<salary>$8,500</salary>
					<hireDate>02/20/1990</hireDate>
				</employee>
			</president>

			<vicePresident>
				<employee ID="6"  workWeek="fullTime">
					<image src="face6"></image>
					<name>
						<firstName>Logan</firstName>
						<midName>Grace</midName>
						<lastName>Hartley</lastName>
					</name>
					<telephone>202-103-6200</telephone>
					<age>36</age>
					<salary>$9,300</salary>
					<hireDate>02/20/1980</hireDate>
				</employee>
			</vicePresident>
		</topLevel>

		<midLevel>
			<departmentsList>
				<department name="Marketing" diagram_src="diagram1" image_src="dep1">
					<subdepartment name="Public Relations">
						<employeeList>
							<employee ID="36"  workWeek="fullTime">
								<image src="face10"></image>
								<name>
									<firstName>Jane</firstName>
									<midName>Azalee</midName>
									<lastName>Schachter</lastName>
								</name>
								<telephone>202-303-6260</telephone>
								<age>39</age>
								<salary>$6,300</salary>
								<hireDate>02/12/2010</hireDate>
							</employee>
						</employeeList>
					</subdepartment>

					<subdepartment name="Product Marketing Manager">
						<employeeList>
							<employee ID="37"  workWeek="fullTime">
								<image src="face7"></image>
								<name>
									<firstName>Azalee</firstName>
									<midName>Jane</midName>
									<lastName>Hartley</lastName>
								</name>
								<telephone>202-000-6260</telephone>
								<age>39</age>
								<salary>$5,900</salary>
								<hireDate>01/05/2005</hireDate>
							</employee>
						</employeeList>
					</subdepartment>
				</department>

				<department name="Sales" diagram_src="diagram2" image_src="dep2">
					<subdepartment name="Sales Administration">
						<employeeList>
							<employee ID="7"  workWeek="fullTime">
								<image src="face6"></image>
								<name>
									<firstName>Schachter</firstName>
									<midName>Jane</midName>
									<lastName>Schachter</lastName>
								</name>
								<telephone>202-103-6260</telephone>
								<age>39</age>
								<salary>$5,300</salary>
								<hireDate>02/20/2010</hireDate>
							</employee>

							<employee ID="8"  workWeek="fullTime">
								<image src="face7"></image>
								<name>
									<firstName>Leonida</firstName>
									<midName>Louise</midName>
									<lastName>Sok</lastName>
								</name>
								<telephone>203-103-6260</telephone>
								<age>40</age>
								<salary>$3,300</salary>
								<hireDate>08/20/2010</hireDate>
							</employee>
						</employeeList>
					</subdepartment>

					<subdepartment name="Inside Sales">
						<employeeList>
							<employee ID="9"  workWeek="partTime">
								<image src="face8"></image>
								<name>
									<firstName>Emanuela</firstName>
									<midName>Jade</midName>
									<lastName>Violette</lastName>
								</name>
								<telephone>233-103-6260</telephone>
								<age>36</age>
								<salary>$5,300</salary>
								<hireDate>08/21/2010</hireDate>
							</employee>

							<employee ID="10"  workWeek="partTime">
								<image src="face9"></image>
								<name>
									<firstName>Hyo</firstName>
									<midName>May</midName>
									<lastName>Bastin</lastName>
								</name>
								<telephone>239-103-6260</telephone>
								<age>49</age>
								<salary>$5,250</salary>
								<hireDate>08/21/2005</hireDate>
							</employee>
						</employeeList>
					</subdepartment>

					<subdepartment name="Business Operations">
						<employeeList>
							<employee ID="11"  workWeek="fullTime">
								<image src="face10"></image>
								<name>
									<firstName>Audra</firstName>
									<midName>Elizabeth</midName>
									<lastName>Myricks</lastName>
								</name>
								<telephone>239-103-6260</telephone>
								<age>60</age>
								<salary>$5,250</salary>
								<hireDate>06/23/2005</hireDate>
							</employee>

							<employee ID="12"  workWeek="partTime">
								<image src="face11"></image>
								<name>
									<firstName>Mason</firstName>
									<midName>Marie</midName>
									<lastName>Lasseter</lastName>
